name: ordering-backgroundtasks

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - Code/Homework/src/BuildingBlocks/**
    - Code/Homework/src/Services/Ordering/**
    - .github/workflows/ordering-backgroundtasks.yml
  
  pull_request:
    branches:
    - main

    paths:
    - Code/Homework/src/BuildingBlocks/**
    - Code/Homework/src/Services/Ordering/**
    - .github/workflows/ordering-backgroundtasks.yml

env:
  SERVICE: ordering-backgroundtasks
  IMAGE: ordering.backgroundtasks

jobs:
  BuildLinux:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build and push image
      uses: ./.github/workflows/composite/build-push
      with:
        service: ${{ env.SERVICE }}
        service_path: Services/Ordering/Ordering.BackgroundTasks
        registry_host: ${{ secrets.REGISTRY_HOST }}
        registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
        image_name: ${{ env.IMAGE }}
        registry_username: ${{ secrets.USERNAME }}
        registry_password: ${{ secrets.PASSWORD }}
