name: payment-api

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - Code/Homework/src/BuildingBlocks/**
    - Code/Homework/src/Services/Payment/**
    - .github/workflows/payment-api.yml
  
  pull_request:
    branches:
    - main

    paths:
    - Code/Homework/src/BuildingBlocks/**
    - Code/Homework/src/Services/Payment/**
    - .github/workflows/payment-api.yml

env:
  SERVICE: payment-api
  IMAGE: payment.api

jobs:
  BuildLinux:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build and push image
      uses: ./.github/workflows/composite/build-push
      with:
        service: ${{ env.SERVICE }}
        service_path: Services/Payment/Payment.API
        registry_host: ${{ secrets.REGISTRY_HOST }}
        registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
        image_name: ${{ env.IMAGE }}
        registry_username: ${{ secrets.USERNAME }}
        registry_password: ${{ secrets.PASSWORD }}
